export const protectedRoutes = [
  "/login",
  "/student/dashboard",
  "/student/profile",
  "/student/bookings",
  "/student/reviews",
  "/tutor/dashboard",
  "/tutor/profile",
  "/tutor/requests",
  "/tutor/earnings",
  "/tutor/subjects",
  "/tutor/availability",
  "/checkout",
  "/checkout/payment",
];
